"""
Bluesky (atproto) client.

Posts new briefings to a Bluesky account using the official atproto
HTTP API. We deliberately avoid the `atproto` Python SDK to keep the
dependency surface small — the three calls we need (createSession,
uploadBlob, createRecord) are straightforward HTTP and the SDK pulls
in pydantic v2 + multiple transitive packages we don't use elsewhere.

Authentication: handle + app password. The app password is generated in
Bluesky Settings → Privacy and Security → App Passwords and is
revocable independently of the account password. Never use the actual
account password here — Bluesky explicitly warns against it for
automation.

Posting model:
    Each post is "social_hook + rich link card" — NOT "title + naked
    URL". The hook is conversational analyst voice (generated by the
    LLM on each blog post). The link card carries the title,
    description, and OG image; the URL never appears as plain text.
    No hashtags — they read like SEO cosplay in this register.

Rate limits: Bluesky publishes per-account write limits of ~5,000
points/hour where a createRecord costs 3 points and uploadBlob costs
much less. We're nowhere near that. The runner caps us at
bluesky_max_per_run (default 5) per cron.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone

import httpx

from src.config import settings


logger = logging.getLogger(__name__)


_BASE = "https://bsky.social/xrpc"
_CREATE_SESSION = f"{_BASE}/com.atproto.server.createSession"
_CREATE_RECORD = f"{_BASE}/com.atproto.repo.createRecord"
_UPLOAD_BLOB = f"{_BASE}/com.atproto.repo.uploadBlob"
_DELETE_RECORD = f"{_BASE}/com.atproto.repo.deleteRecord"

# Bluesky post text limit (graphemes — for ASCII this == characters).
# We leave a small safety margin because byte/grapheme counting differs
# slightly from char counting for emoji and accented characters.
_MAX_POST_CHARS = 290

# Bluesky rejects uploadBlob payloads larger than ~1 MB. Our static
# OG image is well under that, but we cap defensively for any future
# per-post images.
_MAX_BLOB_BYTES = 950_000


@dataclass
class BlueskyResult:
    success: bool
    status_code: int | None
    response_snippet: str
    post_uri: str | None = None  # at://did:plc:.../app.bsky.feed.post/<rkey>
    post_url: str | None = None  # https://bsky.app/profile/<handle>/post/<rkey>


@dataclass
class LinkCard:
    """Bluesky rich link card payload (app.bsky.embed.external)."""
    uri: str
    title: str
    description: str
    thumb_blob: dict | None = None  # blob ref returned by uploadBlob


class BlueskyClient:
    """Thin atproto client. One instance per cron run is fine — sessions
    are valid for ~2 hours; we don't bother refreshing because each
    cron run finishes in seconds."""

    def __init__(self, handle: str, app_password: str):
        self.handle = handle
        self.app_password = app_password
        self._access_jwt: str | None = None
        self._did: str | None = None

    # ── auth ───────────────────────────────────────────────────────────

    def _login(self) -> bool:
        try:
            resp = httpx.post(
                _CREATE_SESSION,
                json={"identifier": self.handle, "password": self.app_password},
                timeout=15,
            )
        except Exception as exc:
            logger.error("bluesky: login HTTP error: %s", exc)
            return False

        if resp.status_code != 200:
            logger.error("bluesky: login failed %d -- %s", resp.status_code, (resp.text or "")[:300])
            return False

        data = resp.json()
        self._access_jwt = data.get("accessJwt")
        self._did = data.get("did")
        if not self._access_jwt or not self._did:
            logger.error("bluesky: login response missing accessJwt/did: %s", data)
            return False

        logger.info("bluesky: logged in as %s (did=%s)", self.handle, self._did)
        return True

    def ensure_session(self) -> bool:
        if self._access_jwt and self._did:
            return True
        return self._login()

    # ── blob upload (for link card thumbnails) ─────────────────────────

    def upload_blob(self, image_bytes: bytes, mime_type: str = "image/png") -> dict | None:
        """Upload raw bytes as a blob and return the blob ref dict.
        That ref is what gets embedded in subsequent post records.
        Returns None on failure (caller should fall back to a card
        without a thumbnail rather than failing the whole post)."""
        if not self.ensure_session():
            return None
        if not image_bytes:
            return None
        if len(image_bytes) > _MAX_BLOB_BYTES:
            logger.warning(
                "bluesky: blob too large (%d bytes); skipping thumbnail",
                len(image_bytes),
            )
            return None

        try:
            resp = httpx.post(
                _UPLOAD_BLOB,
                headers={
                    "Authorization": f"Bearer {self._access_jwt}",
                    "Content-Type": mime_type,
                },
                content=image_bytes,
                timeout=20,
            )
        except Exception as exc:
            logger.warning("bluesky: uploadBlob HTTP error: %s", exc)
            return None

        if resp.status_code != 200:
            logger.warning("bluesky: uploadBlob %d -- %s", resp.status_code, (resp.text or "")[:300])
            return None

        try:
            return resp.json().get("blob")
        except Exception:
            return None

    def upload_image_from_url(self, image_url: str) -> dict | None:
        """Convenience: fetch image_url and upload it as a blob."""
        try:
            r = httpx.get(image_url, timeout=15, follow_redirects=True)
        except Exception as exc:
            logger.warning("bluesky: image fetch %s failed: %s", image_url, exc)
            return None
        if r.status_code != 200 or not r.content:
            logger.warning("bluesky: image fetch %s -> %d", image_url, r.status_code)
            return None
        mime = r.headers.get("content-type", "image/png").split(";", 1)[0].strip() or "image/png"
        return self.upload_blob(r.content, mime_type=mime)

    # ── post creation ──────────────────────────────────────────────────

    def post(self, text: str, link_card: LinkCard | None = None) -> BlueskyResult:
        """Create a single post.

        If `link_card` is provided, attaches an app.bsky.embed.external
        embed (the "rich link card" rendering) so the URL is shown as a
        title+description+thumbnail card under the text — and the text
        itself stays clean (no inline URL needed).
        """
        if not self.ensure_session():
            return BlueskyResult(success=False, status_code=None, response_snippet="login failed")

        text = (text or "").strip()
        if not text:
            return BlueskyResult(success=False, status_code=None, response_snippet="empty text")

        record: dict = {
            "$type": "app.bsky.feed.post",
            "text": text,
            "createdAt": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "langs": ["en"],
        }

        if link_card is not None:
            external: dict = {
                "uri": link_card.uri,
                "title": (link_card.title or "")[:300],
                "description": (link_card.description or "")[:1000],
            }
            if link_card.thumb_blob:
                external["thumb"] = link_card.thumb_blob
            record["embed"] = {
                "$type": "app.bsky.embed.external",
                "external": external,
            }

        try:
            resp = httpx.post(
                _CREATE_RECORD,
                headers={"Authorization": f"Bearer {self._access_jwt}"},
                json={
                    "repo": self._did,
                    "collection": "app.bsky.feed.post",
                    "record": record,
                },
                timeout=15,
            )
        except Exception as exc:
            logger.error("bluesky: createRecord HTTP error: %s", exc)
            return BlueskyResult(success=False, status_code=None, response_snippet=f"http error: {exc}"[:500])

        body = resp.text or ""
        snippet = body[:500]

        if resp.status_code == 200:
            data = resp.json()
            uri = data.get("uri")  # at://did:plc:xxx/app.bsky.feed.post/<rkey>
            rkey = uri.rsplit("/", 1)[-1] if uri else None
            post_url = f"https://bsky.app/profile/{self.handle}/post/{rkey}" if rkey else None
            logger.info("bluesky: posted -> %s", post_url or uri)
            return BlueskyResult(
                success=True,
                status_code=200,
                response_snippet=snippet,
                post_uri=uri,
                post_url=post_url,
            )

        logger.warning("bluesky: %d -- %s", resp.status_code, snippet)
        return BlueskyResult(success=False, status_code=resp.status_code, response_snippet=snippet)

    # ── post deletion (used by the one-off cleanup script) ─────────────

    def delete_post(self, rkey: str) -> bool:
        if not self.ensure_session():
            return False
        try:
            resp = httpx.post(
                _DELETE_RECORD,
                headers={"Authorization": f"Bearer {self._access_jwt}"},
                json={
                    "repo": self._did,
                    "collection": "app.bsky.feed.post",
                    "rkey": rkey,
                },
                timeout=15,
            )
        except Exception as exc:
            logger.error("bluesky: deleteRecord HTTP error: %s", exc)
            return False

        if resp.status_code == 200:
            logger.info("bluesky: deleted rkey=%s", rkey)
            return True
        logger.warning("bluesky: deleteRecord %d -- %s", resp.status_code, (resp.text or "")[:200])
        return False


# ---------------------------------------------------------------------------
# Post composition
# ---------------------------------------------------------------------------


def compose_post(*, social_hook: str | None, title: str) -> str:
    """Compose the visible TEXT of a Bluesky post.

    The text is the conversational hook only — the URL, title, and
    description live in the attached rich link card embed. This is the
    deliberate "modern" format: a human-sounding sentence, then the
    card preview, no hashtags, no naked URL.

    Falls back to the title if the hook is missing (legacy posts that
    were generated before social_hook existed; the backfill script
    should populate them but we degrade gracefully if not).
    """
    hook = (social_hook or "").strip()
    if hook:
        if len(hook) > _MAX_POST_CHARS:
            hook = hook[: _MAX_POST_CHARS - 1].rstrip()
            # Avoid mid-word ellipsis where possible.
            if " " in hook:
                hook = hook[: hook.rfind(" ")]
            hook = hook + "…"
        return hook

    # Fallback: just the title.
    fallback = (title or "").strip()
    if len(fallback) > _MAX_POST_CHARS:
        fallback = fallback[: _MAX_POST_CHARS - 1].rstrip() + "…"
    return fallback


# ---------------------------------------------------------------------------
# Module-level loader
# ---------------------------------------------------------------------------


def is_enabled() -> bool:
    return bool(settings.bluesky_handle.strip() and settings.bluesky_app_password.strip())


def get_client() -> BlueskyClient | None:
    if not is_enabled():
        return None
    return BlueskyClient(
        handle=settings.bluesky_handle.strip(),
        app_password=settings.bluesky_app_password.strip(),
    )
